### ISSUE TITLE
After set selected element to 0 it shows placeholder instead of element from array

### ISSUE THREAD

**Issue by viktorchukhantsev** [Darkseal/DownPicker#20]
After set selected element to 0 it shows placeholder instead of element from array.

```
[self.downPicker setSelectedIndex:0];
```

but

```
[self.downPicker getValueAtIndex:0];
```

returns right value

**Comment by Darkseal** [comment]
0.1.30 should fix this issue for good. 

Notice that the behaviour of setSelectedIndex changed, now you must use -1 instead of `nil` to clear the selection. I was force to modify that because nil evaluates to 0 in Objective-C (that was the source of your initial issue). Hope the fix will work for you.
